"""Notebook tailoring — the GENERATE step (Phase 2B).

Takes the architecture plan (Phase 2A) and generates the actual notebook,
section by section — one Nemotron call per service (D5: section decomposition,
no monolithic call that times out). Each code cell is tagged with its
service_id, so the manifest's cellRefs link visualizer nodes to the exact cells
that implement them (D3/D4).

Output:
  <name>.tailored.ipynb   — the notebook
  <name>.manifest.json    — the ArchitectureManifest (visualizer-ready)

Test standalone (no NAT). Makes one Nemotron call per service, so it takes a
bit and costs a few NIM credits:
    python -m sdk_orchestrator.generate "HIPAA-compliant clinical chatbot"
"""

from __future__ import annotations

import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

import nbformat

from sdk_orchestrator import nim
from sdk_orchestrator.manifest import (
    ArchitectureManifest,
    ManifestConnection,
    ManifestProvenance,
    ManifestService,
    summarize,
)
from sdk_orchestrator.plan import _load_blueprint_text, plan_architecture

OUT_DIR = Path(__file__).resolve().parents[1] / "out"

SECTION_SYSTEM_PROMPT = """You are a senior NVIDIA AI engineer writing one section
of a production Jupyter notebook.

Generate the cells that implement a single NVIDIA service for the given use case,
in its specific role. Ground on the reference blueprint excerpt — reuse its real
API calls, helper names, and patterns. Do NOT invent API calls or function names.

Return ONLY a JSON object of this exact shape:
{
  "cells": [
    {"type": "markdown", "source": "## <section heading>\\n<1-2 line purpose>"},
    {"type": "code", "source": "<python>"}
  ]
}

Rules:
- Exactly one leading markdown cell (the section heading + purpose), then 1-3 code cells.
- Use REAL NVIDIA APIs from the blueprint. No hallucinated symbols or CLIs.
- Keep code runnable; use os.environ[...] for secrets, never literals.
- Output valid JSON only. No prose, no markdown fences.
"""


def _clean_cells(cells: list) -> list[dict]:
    """Keep only well-formed cells with non-empty source.

    Filters out the failure modes seen in practice: blank cells, missing
    source, and cells whose source is just leaked JSON structure (e.g. a
    trailing '}]}' artifact from the model's response bleeding through).
    """
    out = []
    for c in cells:
        if not isinstance(c, dict):
            continue
        ctype = c.get("type")
        src = c.get("source")
        if ctype not in ("markdown", "code") or not isinstance(src, str):
            continue
        src = src.strip()
        if not src:
            continue
        # reject sources that are only JSON punctuation (leaked structure)
        if all(ch in "{}[]\":, \n\t" for ch in src):
            continue
        out.append({"type": ctype, "source": src})
    return out


def generate_section(service: dict, use_case: str, blueprint_text: str, _retry: bool = True) -> list[dict]:
    """Generate cells for one service. Returns cleaned [{type, source}, ...].

    Retries once if the first attempt yields no usable cells — the model is
    not output-stable across calls, and an empty section must not silently
    become blank cells with fake cellRefs (the bug seen on triton/nim).
    """
    user = (
        f"USE CASE:\n{use_case}\n\n"
        f"SERVICE: {service['name']} (id: {service['id']})\n"
        f"ROLE IN THIS SOLUTION: {service['role']}\n\n"
    )
    if blueprint_text:
        user += f"REFERENCE BLUEPRINT EXCERPT — ground on this:\n{blueprint_text[:8000]}\n"

    from sdk_orchestrator.plan import _extract_json

    raw = nim.chat(
        messages=[
            {"role": "system", "content": SECTION_SYSTEM_PROMPT},
            {"role": "user", "content": user},
        ],
        json_mode=True,
        thinking=False,
        temperature=0.0,
    )
    cells = _clean_cells(_extract_json(raw).get("cells", []))

    if not cells and _retry:
        print(f"[generate] {service['id']}: empty, retrying once…", file=sys.stderr)
        return generate_section(service, use_case, blueprint_text, _retry=False)
    if not cells:
        print(f"[generate] WARNING: {service['id']} produced no usable cells after retry", file=sys.stderr)
    return cells


def tailor_notebook(use_case: str, blueprint_id: str | None = None) -> dict:
    """Plan the architecture, generate each section, assemble notebook + manifest."""
    plan = plan_architecture(use_case, blueprint_id)
    services_plan = plan["services"]
    blueprint_id = plan["blueprint_id"]
    blueprint_text = _load_blueprint_text(blueprint_id) if blueprint_id else ""

    nb = nbformat.v4.new_notebook()
    nb_cells: list = []
    manifest_services: list[ManifestService] = []
    code_cell_count = 0

    # Title + overview
    nb_cells.append(
        nbformat.v4.new_markdown_cell(
            f"# {use_case}\n\n"
            f"Generated by NVIDIA SDK Orchestrator. Grounded on blueprint: "
            f"`{blueprint_id or 'none'}`."
        )
    )

    # One section per service; track which cell indices implement each service.
    for svc in services_plan:
        print(f"[generate] section: {svc['id']} …", file=sys.stderr)
        section = generate_section(svc, use_case, blueprint_text)

        # Honest handling of a section that failed to generate: do NOT emit
        # blank cells with cellRefs claiming implementation (the triton/nim
        # bug). Mark the service unresolved with empty cellRefs and a visible
        # note cell, so the manifest tells the truth.
        if not section:
            nb_cells.append(
                nbformat.v4.new_markdown_cell(
                    f"## {svc['name']}\n\n"
                    f"_Section generation failed — needs regeneration or manual authoring._"
                )
            )
            manifest_services.append(
                ManifestService(
                    id=svc["id"], name=svc["name"], role=svc["role"], layer=svc["layer"],
                    cellRefs=[], verification="unresolved",
                )
            )
            continue

        cell_refs: list[int] = []
        for cell in section:
            idx = len(nb_cells)
            if cell["type"] == "markdown":
                nb_cells.append(nbformat.v4.new_markdown_cell(cell["source"]))
            else:
                nb_cells.append(
                    nbformat.v4.new_code_cell(cell["source"], metadata={"service_id": svc["id"]})
                )
                cell_refs.append(idx)  # cellRefs point at the CODE cells
                code_cell_count += 1

        manifest_services.append(
            ManifestService(
                id=svc["id"],
                name=svc["name"],
                role=svc["role"],
                layer=svc["layer"],
                cellRefs=cell_refs,
                verification="not_run",  # Phase 3 fills this on real GPU
            )
        )

    nb.cells = nb_cells

    # Build the manifest (the visualizer contract).
    connections = [
        ManifestConnection(**{"from": c["from"], "to": c["to"], "data": c["data"]})
        for c in plan["connections"]
    ]
    provenance = ManifestProvenance(
        useCase=use_case,
        blueprintId=blueprint_id,
        model=nim.DEFAULT_REASONER_MODEL,
        agentRunId=uuid.uuid4().hex,
        generatedAt=datetime.now(timezone.utc).isoformat(),
        totalCells=len(nb_cells),
    )
    manifest = ArchitectureManifest(
        provenance=provenance,
        services=manifest_services,
        connections=connections,
        verificationSummary=summarize(manifest_services, code_cell_count),
    )

    # Write artifacts.
    OUT_DIR.mkdir(exist_ok=True)
    slug = "".join(ch if ch.isalnum() else "-" for ch in use_case.lower())[:40].strip("-")
    nb_path = OUT_DIR / f"{slug}.tailored.ipynb"
    mf_path = OUT_DIR / f"{slug}.manifest.json"
    nbformat.write(nb, str(nb_path))
    mf_path.write_text(manifest.to_visualizer_json(), encoding="utf-8")

    return {
        "notebook_path": str(nb_path),
        "manifest_path": str(mf_path),
        "services": len(manifest_services),
        "code_cells": code_cell_count,
        "total_cells": len(nb_cells),
    }


def _cli() -> int:
    if len(sys.argv) < 2:
        print('usage: python -m sdk_orchestrator.generate "<use case>"', file=sys.stderr)
        return 2
    result = tailor_notebook(" ".join(sys.argv[1:]))
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
